// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBnB.Migrations
{
    [DbContext(typeof(AirBnBContext))]
    [Migration("20230410133759_ChangedSeeding")]
    partial class ChangedSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirBnB.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "djoekeduijker@live.nl",
                            FirstName = "Djoeke",
                            LastName = "Duijker"
                        },
                        new
                        {
                            Id = 2,
                            Email = "theoharissgouridis@gmail.com",
                            FirstName = "Theoharis",
                            LastName = "Sgouridis"
                        });
                });

            modelBuilder.Entity("AirBnB.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCover = false,
                            Url = "https://dq1eylutsoz4u.cloudfront.net/2019/12/20060024/adult-man-baby-boomer-clean-cut_t20_b8wV6V-800x600-50-year-old-man.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsCover = false,
                            Url = "https://as1.ftcdn.net/v2/jpg/04/70/50/70/1000_F_470507000_FxGToXZnkwPgMYAc5KdX9SvtlYLjPhKf.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsCover = true,
                            LocationId = 1,
                            Url = "https://www.integervastgoed.nl/img/oasis-city-almere-1.png"
                        },
                        new
                        {
                            Id = 4,
                            IsCover = true,
                            LocationId = 2,
                            Url = "https://assets-global.website-files.com/604668223c6f81ba87398bd4/60a2585a0441561aaca31be4_vooraanzicht%20woning.jpg"
                        },
                        new
                        {
                            Id = 5,
                            IsCover = true,
                            LocationId = 3,
                            Url = "https://www.thespruce.com/thmb/iMt63n8NGCojUETr6-T8oj-5-ns=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/PAinteriors-7-cafe9c2bd6be4823b9345e591e4f367f.jpg"
                        },
                        new
                        {
                            Id = 6,
                            IsCover = true,
                            LocationId = 3,
                            Url = "https://images.squarespace-cdn.com/content/v1/5b097b4a4cde7ab1c2125706/90f9b45a-0c57-44b0-a566-53e4359a817e/CathieHong_Bookins_2.jpg?format=300w"
                        },
                        new
                        {
                            Id = 7,
                            IsCover = false,
                            LocationId = 1,
                            Url = "https://theartofliving.nl/wp-content/uploads/2022/12/A1U-Maatwerk-Rob-Feenstra_12.jpg"
                        },
                        new
                        {
                            Id = 8,
                            IsCover = false,
                            LocationId = 2,
                            Url = "https://www.drijvers-oisterwijk.nl/wp-content/uploads/2019/01/3201-Drijvers-Oisterwijk-interieur-restauratie-modern-landelijk-houten-spant-strak-licht-maatwerk-12.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsCover = true,
                            LocationId = 3,
                            Url = "https://images.squarespace-cdn.com/content/v1/5b097b4a4cde7ab1c2125706/90f9b45a-0c57-44b0-a566-53e4359a817e/CathieHong_Bookins_2.jpg?format=750w"
                        },
                        new
                        {
                            Id = 10,
                            IsCover = true,
                            LocationId = 4,
                            Url = "https://www.hoiveluwe.nl/custom/page/page_content_img/34780_original.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsCover = true,
                            LocationId = 5,
                            Url = "https://www.specialhotels.nl/foto/foto_800_450/26073.jpg"
                        },
                        new
                        {
                            Id = 12,
                            IsCover = true,
                            LocationId = 6,
                            Url = "https://040houserental.nl/wp-content/uploads/2022/01/DSC_0011_5_1.jpg"
                        },
                        new
                        {
                            Id = 13,
                            IsCover = true,
                            LocationId = 7,
                            Url = "https://media.indebuurt.nl/breda/2022/07/18140124/Miza-Bergen-op-Zoom.jpg"
                        },
                        new
                        {
                            Id = 14,
                            IsCover = true,
                            LocationId = 8,
                            Url = "https://www.ruralcoast.com/galeria/inmuebles/chalet-indep-polop-1734-1.jpg"
                        },
                        new
                        {
                            Id = 15,
                            IsCover = true,
                            LocationId = 9,
                            Url = "https://cloud.funda.nl/valentina_media/119/434/724_1080x720.jpg"
                        },
                        new
                        {
                            Id = 16,
                            IsCover = true,
                            LocationId = 10,
                            Url = "https://images.oyoroomscdn.com/uploads/hotel_image/100011873/medium/88812_lsr_2020052255142949050.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsCover = false,
                            Url = "https://st4.depositphotos.com/3429495/38405/i/600/depositphotos_384057762-stock-photo-cannes-france-may-karin-viard.jpg"
                        },
                        new
                        {
                            Id = 18,
                            IsCover = false,
                            LocationId = 4,
                            Url = "https://dotnlgul4mfwg.cloudfront.net/wp-content/uploads/2018/04/13124619/boshuis_friesche_duin17__inline_staand_groot.jpg"
                        },
                        new
                        {
                            Id = 19,
                            IsCover = false,
                            LocationId = 5,
                            Url = "https://interiorjunkie.com/wp-content/uploads/2020/10/hotel-chic-badkamer-2-685x1024.jpg"
                        },
                        new
                        {
                            Id = 20,
                            IsCover = false,
                            LocationId = 6,
                            Url = "https://images.homify.com/c_fill,f_auto,q_0,w_740/v1560373677/p/photo/image/3088926/P2_APRES.jpg"
                        },
                        new
                        {
                            Id = 21,
                            IsCover = false,
                            LocationId = 7,
                            Url = "https://www.inrichting-huis.com/wp-content/afbeeldingen/interieur-appartement-hotelsfeer.jpg"
                        },
                        new
                        {
                            Id = 22,
                            IsCover = false,
                            LocationId = 8,
                            Url = "https://www.ruralcoast.com/galeria/inmuebles/chalet-indep-polop-1734-4.jpg"
                        },
                        new
                        {
                            Id = 23,
                            IsCover = false,
                            LocationId = 9,
                            Url = "https://img.vtwonen.nl/8a4eb93b559d0a56f0161a681c9fe9da5b2d52fd/5x-binnenkijken-in-een-monumentaal-pand"
                        },
                        new
                        {
                            Id = 24,
                            IsCover = false,
                            LocationId = 10,
                            Url = "https://images.oyoroomscdn.com/uploads/hotel_image/100011873/medium/88812_lsr_202002084173854678.jpg"
                        },
                        new
                        {
                            Id = 25,
                            IsCover = true,
                            LocationId = 11,
                            Url = "https://www.standout-cabin-designs.com/images/small-stone-cottages1a.jpg"
                        },
                        new
                        {
                            Id = 26,
                            IsCover = false,
                            LocationId = 11,
                            Url = "https://usenaturalstone.org/wp-content/uploads/2016/03/Megy-Article-1.jpg"
                        });
                });

            modelBuilder.Entity("AirBnB.Models.Landlord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Landlords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 55,
                            AvatarId = 1,
                            Email = "keesvdspek@gmail.com",
                            FirstName = "Kees",
                            LastName = "van der Spek",
                            Phone = "12345678"
                        },
                        new
                        {
                            Id = 2,
                            Age = 61,
                            AvatarId = 2,
                            Email = "geertjan@gmail.com",
                            FirstName = "Geert-Jan",
                            LastName = "Barends",
                            Phone = "12345678"
                        },
                        new
                        {
                            Id = 3,
                            Age = 45,
                            AvatarId = 17,
                            Email = "karinjanssen@gmail.com",
                            FirstName = "Karin",
                            LastName = "Janssen",
                            Phone = "12345678"
                        });
                });

            modelBuilder.Entity("AirBnB.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Features")
                        .HasColumnType("int");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Huis in het centrum",
                            Features = 52,
                            LandlordId = 1,
                            LocationType = 0,
                            NumberOfGuests = 3,
                            PricePerDay = 50.99f,
                            Rooms = 3,
                            SubTitle = "Huis word al jaren goed bevonden door 100+ klanten",
                            Title = "Almere Apartement"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Boerderij huisje, lekker afgelegen en dieren zijn toegestaan",
                            Features = 22,
                            LandlordId = 2,
                            LocationType = 5,
                            NumberOfGuests = 10,
                            PricePerDay = 500.99f,
                            Rooms = 4,
                            SubTitle = "Prijzig, maar een echte landelijke ervaring.",
                            Title = "Woonboerderij"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kamer voor 2 personen",
                            Features = 4,
                            LandlordId = 1,
                            LocationType = 3,
                            NumberOfGuests = 2,
                            PricePerDay = 20.99f,
                            Rooms = 1,
                            SubTitle = "Kamer op een rustig gelegen plek dichtbij de stad",
                            Title = "Kamer in Almere"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gezellig chalet in de bossen",
                            Features = 6,
                            LandlordId = 3,
                            LocationType = 2,
                            NumberOfGuests = 4,
                            PricePerDay = 80.99f,
                            Rooms = 2,
                            SubTitle = "Verblijf midden in de natuur",
                            Title = "Chalet in de bossen"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ruim opgezet hotel met uitzicht op zee",
                            Features = 36,
                            LandlordId = 1,
                            LocationType = 4,
                            NumberOfGuests = 2,
                            PricePerDay = 120.5f,
                            Rooms = 5,
                            SubTitle = "Geniet van luxe en comfort",
                            Title = "Zeezicht hotel"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gezellige studio in het centrum",
                            Features = 4,
                            LandlordId = 3,
                            LocationType = 3,
                            NumberOfGuests = 2,
                            PricePerDay = 60.99f,
                            Rooms = 1,
                            SubTitle = "Perfect voor een stedentrip",
                            Title = "Studio in Amsterdam"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Rustig gelegen appartement aan de rand van de stad",
                            Features = 28,
                            LandlordId = 1,
                            LocationType = 0,
                            NumberOfGuests = 4,
                            PricePerDay = 90f,
                            Rooms = 3,
                            SubTitle = "Ontsnap aan de drukte van de stad",
                            Title = "Appartement aan de rand van de stad"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Moderne villa met zwembad en uitzicht op de bergen",
                            Features = 28,
                            LandlordId = 2,
                            LocationType = 5,
                            NumberOfGuests = 6,
                            PricePerDay = 350f,
                            Rooms = 4,
                            SubTitle = "Luxe villa met veel privacy",
                            Title = "Villa met zwembad en bergzicht"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Gezellig appartement in historisch pand",
                            Features = 28,
                            LandlordId = 2,
                            LocationType = 0,
                            NumberOfGuests = 3,
                            PricePerDay = 75f,
                            Rooms = 2,
                            SubTitle = "Historische sfeer gecombineerd met modern comfort",
                            Title = "Appartement in historisch pand"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Comfortabel vakantiehuis met privétuin",
                            Features = 22,
                            LandlordId = 3,
                            LocationType = 5,
                            NumberOfGuests = 8,
                            PricePerDay = 180f,
                            Rooms = 3,
                            SubTitle = "Ideaal voor gezinnen of groepen vrienden",
                            Title = "Vakantiehuis met privétuin"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Een leuk uitje voor met zijn twee of een klein gezin",
                            Features = 4,
                            LandlordId = 3,
                            LocationType = 1,
                            NumberOfGuests = 3,
                            PricePerDay = 30f,
                            Rooms = 3,
                            SubTitle = "Leuke cottage",
                            Title = "Een stenen cottage"
                        });
                });

            modelBuilder.Entity("AirBnB.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Discount = 0f,
                            EndDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            StartDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Discount = 0f,
                            EndDate = new DateTime(2022, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            StartDate = new DateTime(2022, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AirBnB.Models.Image", b =>
                {
                    b.HasOne("AirBnB.Models.Location", null)
                        .WithMany("Images")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("AirBnB.Models.Landlord", b =>
                {
                    b.HasOne("AirBnB.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("AirBnB.Models.Location", b =>
                {
                    b.HasOne("AirBnB.Models.Landlord", "Landlord")
                        .WithMany("Locations")
                        .HasForeignKey("LandlordId");

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("AirBnB.Models.Reservation", b =>
                {
                    b.HasOne("AirBnB.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBnB.Models.Location", "Location")
                        .WithMany("Reservations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AirBnB.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirBnB.Models.Landlord", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("AirBnB.Models.Location", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
